export enum YouTubeMcpErrorCode {
  // Auth
  AUTH_NOT_CONFIGURED = "AUTH_NOT_CONFIGURED",
  AUTH_REQUIRED = "AUTH_REQUIRED",
  AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED",
  AUTH_REFRESH_FAILED = "AUTH_REFRESH_FAILED",
  AUTH_INSUFFICIENT_SCOPE = "AUTH_INSUFFICIENT_SCOPE",

  // Validation
  INVALID_PARAMS = "INVALID_PARAMS",
  MISSING_REQUIRED_PARAM = "MISSING_REQUIRED_PARAM",
  INVALID_DATE_FORMAT = "INVALID_DATE_FORMAT",
  INVALID_FILE_PATH = "INVALID_FILE_PATH",
  FILE_TOO_LARGE = "FILE_TOO_LARGE",
  PUBLISH_DATE_IN_PAST = "PUBLISH_DATE_IN_PAST",

  // YouTube API resource errors
  VIDEO_NOT_FOUND = "VIDEO_NOT_FOUND",
  PLAYLIST_NOT_FOUND = "PLAYLIST_NOT_FOUND",
  CHANNEL_NOT_FOUND = "CHANNEL_NOT_FOUND",
  COMMENT_NOT_FOUND = "COMMENT_NOT_FOUND",
  PLAYLIST_ITEM_NOT_FOUND = "PLAYLIST_ITEM_NOT_FOUND",

  // YouTube API permission/quota errors
  PERMISSION_DENIED = "PERMISSION_DENIED",
  QUOTA_EXCEEDED = "QUOTA_EXCEEDED",
  RATE_LIMITED = "RATE_LIMITED",

  // Operation errors
  VIDEO_UPLOAD_FAILED = "VIDEO_UPLOAD_FAILED",
  INVALID_VIDEO_ID = "INVALID_VIDEO_ID",

  // System
  INTERNAL_ERROR = "INTERNAL_ERROR",
  NETWORK_UNREACHABLE = "NETWORK_UNREACHABLE",
}
